-- Expand DataCategory Enum
ALTER TYPE "DataCategory" ADD VALUE IF NOT EXISTS 'TRANSPORT';
ALTER TYPE "DataCategory" ADD VALUE IF NOT EXISTS 'POLICE';
ALTER TYPE "DataCategory" ADD VALUE IF NOT EXISTS 'BANKING';
ALTER TYPE "DataCategory" ADD VALUE IF NOT EXISTS 'WELFARE';
ALTER TYPE "DataCategory" ADD VALUE IF NOT EXISTS 'MUNICIPAL';

-- Expand WorkflowState Enum
ALTER TYPE "WorkflowState" ADD VALUE IF NOT EXISTS 'TRANSPORT_VERIFY';
ALTER TYPE "WorkflowState" ADD VALUE IF NOT EXISTS 'POLICE_VERIFY';
ALTER TYPE "WorkflowState" ADD VALUE IF NOT EXISTS 'BANKING_VERIFY';
ALTER TYPE "WorkflowState" ADD VALUE IF NOT EXISTS 'WELFARE_VERIFY';

-- AlterTable Citizen
ALTER TABLE "Citizen" ADD COLUMN IF NOT EXISTS "onegovId" TEXT;
ALTER TABLE "Citizen" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Citizen" ADD COLUMN IF NOT EXISTS "dateOfBirth" TEXT;
ALTER TABLE "Citizen" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "Citizen" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Citizen" ADD COLUMN IF NOT EXISTS "district" TEXT;
ALTER TABLE "Citizen" ADD COLUMN IF NOT EXISTS "pincode" TEXT;
ALTER TABLE "Citizen" ADD COLUMN IF NOT EXISTS "primaryAddress" TEXT;

-- AlterTable IdentityMap
ALTER TABLE "IdentityMap" ADD COLUMN IF NOT EXISTS "transportDeptId" TEXT;
ALTER TABLE "IdentityMap" ADD COLUMN IF NOT EXISTS "policeDeptId" TEXT;
ALTER TABLE "IdentityMap" ADD COLUMN IF NOT EXISTS "bankingDeptId" TEXT;
ALTER TABLE "IdentityMap" ADD COLUMN IF NOT EXISTS "welfareDeptId" TEXT;
ALTER TABLE "IdentityMap" ADD COLUMN IF NOT EXISTS "municipalDeptId" TEXT;

-- AlterTable WorkflowRun
ALTER TABLE "WorkflowRun" ADD COLUMN IF NOT EXISTS "serviceType" TEXT NOT NULL DEFAULT 'SCHOLARSHIP';
ALTER TABLE "WorkflowRun" ADD COLUMN IF NOT EXISTS "transportSnapshot" JSONB;
ALTER TABLE "WorkflowRun" ADD COLUMN IF NOT EXISTS "policeSnapshot" JSONB;
ALTER TABLE "WorkflowRun" ADD COLUMN IF NOT EXISTS "bankingSnapshot" JSONB;
ALTER TABLE "WorkflowRun" ADD COLUMN IF NOT EXISTS "welfareSnapshot" JSONB;

-- Create Unique Index
CREATE UNIQUE INDEX IF NOT EXISTS "Citizen_onegovId_key" ON "Citizen"("onegovId");
