/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        sans: ['"Inter"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      colors: {
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        text: 'var(--text)',
        'text-2': 'var(--text-2)',
        'text-muted': 'var(--text-muted)',
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'primary-brand': 'var(--primary-brand)',
        'on-primary': 'var(--on-primary)',
        'primary-tint': 'var(--primary-tint)',
        secondary: 'var(--secondary)',
        'on-secondary': 'var(--on-secondary)',
        'secondary-tint': 'var(--secondary-tint)',
        accent: 'var(--accent)',
        'accent-hi': 'var(--accent-hi)',
        'on-accent': 'var(--on-accent)',
        'accent-tint': 'var(--accent-tint)',
        bronze: 'var(--bronze)',
        'bronze-tint': 'var(--bronze-tint)',
        brown: 'var(--brown)',
        sage: 'var(--sage)',
        'sage-fill': 'var(--sage-fill)',
        'sage-tint': 'var(--sage-tint)',
        salmon: 'var(--salmon)',
        peach: 'var(--peach)',
        tan: 'var(--tan)',
        success: 'var(--success)',
        'success-tint': 'var(--success-tint)',
        warning: 'var(--warning)',
        'warning-fill': 'var(--warning-fill)',
        'warning-tint': 'var(--warning-tint)',
        danger: 'var(--danger)',
        'danger-tint': 'var(--danger-tint)',
        info: 'var(--info)',
        'info-tint': 'var(--info-tint)',
        panel: 'var(--panel)',
        'panel-text': 'var(--panel-text)',
        'panel-text-2': 'var(--panel-text-2)',
        'panel-accent': 'var(--panel-accent)',
        'dept-1': 'var(--dept-1)',
        'dept-2': 'var(--dept-2)',
        'dept-3': 'var(--dept-3)',
        'dept-4': 'var(--dept-4)',
        'dept-5': 'var(--dept-5)',
        'dept-6': 'var(--dept-6)',
        'dept-7': 'var(--dept-7)',
        'dept-8': 'var(--dept-8)',
      },
      fontSize: {
        'display-xl': ['2.5rem', { lineHeight: '1.15', fontWeight: '500' }],
        'display-lg': ['2rem', { lineHeight: '1.2', fontWeight: '600' }],
        'display-md': ['1.5rem', { lineHeight: '1.25', fontWeight: '600' }],
        'heading-sm': ['1.125rem', { lineHeight: '1.35', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.65' }],
        'body-sm': ['0.875rem', { lineHeight: '1.6' }],
        'label': ['0.75rem', { lineHeight: '1', fontWeight: '600', letterSpacing: '0.06em' }],
        'caption': ['0.75rem', { lineHeight: '1.5' }],
        'mono-sm': ['0.8125rem', { lineHeight: '1.5' }],
      },
    },
  },
  plugins: [],
}
