#!/usr/bin/env node
/**
 * export_demo_credentials.js
 * --------------------------
 * Reads the seed citizen data and writes DEMO_CREDENTIALS.md to the repo root.
 * This file is for the presenter's private reference ONLY.
 * It is .gitignored and never imported by the application.
 *
 * Usage: node scripts/export_demo_credentials.js
 * Re-run any time the seed data changes (e.g. when citizens.ts is updated).
 */

const path = require('path');
const fs = require('fs');

// Load citizen data — try the backend TS-compiled version first, then the JS copies
let generate50Citizens;
try {
  // Attempt to require the JS copy from mock services (deterministic_50_citizens.js)
  const mod = require(path.join(__dirname, 'deterministic_50_citizens.js'));
  generate50Citizens = mod.generate50Citizens;
} catch {
  // Fallback: inline the same logic from the mock-identity citizens.js
  const mod = require(path.join(__dirname, '../packages/mock-identity/src/citizens.js'));
  generate50Citizens = mod.generate50Citizens;
}

const citizens = generate50Citizens();

// ── Build Markdown table ──────────────────────────────────────────────────────

const rows = citizens.map((c) => {
  const { num, onegovId, name, email, password, personaTag } = c;
  return `| ${String(num).padStart(2)} | \`${onegovId}\` | ${name} | \`${email}\` | \`${password}\` | ${personaTag} |`;
});

const content = `# GovLink — Demo Persona Credentials Reference

> **PRIVATE — Do not commit, share, or display during a live demo.**  
> Generated by \`scripts/export_demo_credentials.js\` on ${new Date().toISOString()}  
> Re-run after any change to \`packages/backend/src/seed/citizens.ts\`

## All 50 Demo Personas

| # | OneGov ID | Full Name | Email | Password | Scenario / Persona Tag |
|---|---|---|---|---|---|
${rows.join('\n')}

## Notes

- All passwords are \`demo123\` for every persona.
- The live UI **never displays these credentials** — persona cards on the login page are strictly informational references.
- To sign in as any of the 50 registry personas, copy/enter their email and password from this table into the standard login form on the login page.
- Self-registered accounts created via the "Register" tab will have independent credentials and a new Universal Citizen ID (\`OG-2026-9XXXXXXX\`).
`;

const outPath = path.join(__dirname, '..', 'DEMO_CREDENTIALS.md');
fs.writeFileSync(outPath, content, 'utf8');
console.log(`✅  Written → ${outPath}`);
console.log(`    ${citizens.length} personas exported.`);
console.log(`\n⚠️  This file is .gitignored. Do NOT commit it.`);
